backend:
  name: git-gateway
  branch: main   # o la rama donde tengas tu proyecto

media_folder: "public/uploads"   # dónde guardar imágenes
public_folder: "/uploads"

collections:
  - name: "testimonios" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/data/testimonios" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{nombre}}-{{cargo}}" 
    fields:
      - { label: "Nombre", name: "nombre", widget: "text" }
      - { label: "Cargo", name: "cargo", widget: "string" }
